# Generated by Django 3.2.14 on 2022-07-19 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 7, 19, 17, 7, 47, 406828, tzinfo=utc))),
                ('targeted_date', models.DateTimeField(default=datetime.datetime(2022, 7, 19, 17, 7, 47, 406828, tzinfo=utc))),
            ],
        ),
    ]
